version: '3'

services:
  webapp:
    build: 
      context: ./node
      dockerfile: Dockerfile
    entrypoint: wait-for mysql:3306 -t 40 -- node index.js
    networks:
      - node_network
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - webapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_network

networks:
  node_network:
    driver: bridge